ALTER TABLE permissions
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE roles
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE users
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE audit_logs
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE github_cache
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE github_oauth
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE portfolio_sections
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE portfolios
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE templates
    ALTER COLUMN id DROP DEFAULT;

